# Site settings
title: Gus Chiggins
email: jeff@guschiggins.com
description: > # this means to ignore newlines until "baseurl:"
What are you doing here? How did you get here? Gus Chiggins is real.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: guschiggins
github_username:  guschiggins

# Build settings
markdown: kramdown
